#!/usr/bin/env python3

from sys import *

def helper():
    print("USAGE\n\t\t./201yams d1 d2 d3 d4 d5 c \n")
    print("DESCRIPTION\n\t\td1\tvalue of the first die (0 if not thrown")
    print("\t\td2\tvalue of the second die (0 if not thrown)")
    print("\t\td3\tvalue of the third die (0 if not thrown)")
    print("\t\td4\tvalue of the fourth die (0 if not thrown)")
    print("\t\td5\tvalue of the fifth die (0 if not thrown)")
    print("\t\tc\texpected combination")


if __name__ == "__main__":
    if len(argv) == 2 and argv[1] == "-h":
        helper()
    elif len(argv) == 7:
        print("YAMMS!")
    else:
        print("\tINVALID ARGUMENT")
        print("->\ttype \"-h\" for help\t<-")
        exit (84)
